#!/bin/sh
# Usage: script/bootstrap
# Ensures all gems are in vendor/cache and installed locally.
set -e

# github/strap related bootstrapping
if [ "$(uname -s)" = "Darwin" ]; then
  brew update >/dev/null
  brew bundle check &>/dev/null || brew bundle

  brew bootstrap-rbenv-ruby

  BUNDLE="brew bundle exec -- bundle"
else
  BUNDLE="bundle"
fi

$BUNDLE install --binstubs --local --path=vendor/gems
bundle package --all
